/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.gm.hxOracle.dto;

import com.gm.hxOracle.dao.*;
import com.gm.hxOracle.factory.*;
import com.gm.hxOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Employees implements Serializable
{
	/** 
	 * This attribute maps to the column EMPLOYEE_ID in the EMPLOYEES table.
	 */
	protected int employeeId;

	/** 
	 * This attribute maps to the column FIRST_NAME in the EMPLOYEES table.
	 */
	protected String firstName;

	/** 
	 * This attribute maps to the column LAST_NAME in the EMPLOYEES table.
	 */
	protected String lastName;

	/** 
	 * This attribute maps to the column EMAIL in the EMPLOYEES table.
	 */
	protected String email;

	/** 
	 * This attribute maps to the column PHONE_NUMBER in the EMPLOYEES table.
	 */
	protected String phoneNumber;

	/** 
	 * This attribute maps to the column HIRE_DATE in the EMPLOYEES table.
	 */
	protected Date hireDate;

	/** 
	 * This attribute maps to the column JOB_ID in the EMPLOYEES table.
	 */
	protected String jobId;

	/** 
	 * This attribute maps to the column SALARY in the EMPLOYEES table.
	 */
	protected float salary;

	/** 
	 * This attribute represents whether the primitive attribute salary is null.
	 */
	protected boolean salaryNull = true;

	/** 
	 * This attribute maps to the column COMMISSION_PCT in the EMPLOYEES table.
	 */
	protected float commissionPct;

	/** 
	 * This attribute represents whether the primitive attribute commissionPct is null.
	 */
	protected boolean commissionPctNull = true;

	/** 
	 * This attribute maps to the column MANAGER_ID in the EMPLOYEES table.
	 */
	protected int managerId;

	/** 
	 * This attribute represents whether the primitive attribute managerId is null.
	 */
	protected boolean managerIdNull = true;

	/** 
	 * This attribute maps to the column DEPARTMENT_ID in the EMPLOYEES table.
	 */
	protected int departmentId;

	/** 
	 * This attribute represents whether the primitive attribute departmentId is null.
	 */
	protected boolean departmentIdNull = true;

	/**
	 * Method 'Employees'
	 * 
	 */
	public Employees()
	{
	}

	/**
	 * Method 'getEmployeeId'
	 * 
	 * @return int
	 */
	public int getEmployeeId()
	{
		return employeeId;
	}

	/**
	 * Method 'setEmployeeId'
	 * 
	 * @param employeeId
	 */
	public void setEmployeeId(int employeeId)
	{
		this.employeeId = employeeId;
	}

	/**
	 * Method 'getFirstName'
	 * 
	 * @return String
	 */
	public String getFirstName()
	{
		return firstName;
	}

	/**
	 * Method 'setFirstName'
	 * 
	 * @param firstName
	 */
	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	/**
	 * Method 'getLastName'
	 * 
	 * @return String
	 */
	public String getLastName()
	{
		return lastName;
	}

	/**
	 * Method 'setLastName'
	 * 
	 * @param lastName
	 */
	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	/**
	 * Method 'getEmail'
	 * 
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Method 'setEmail'
	 * 
	 * @param email
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/**
	 * Method 'getPhoneNumber'
	 * 
	 * @return String
	 */
	public String getPhoneNumber()
	{
		return phoneNumber;
	}

	/**
	 * Method 'setPhoneNumber'
	 * 
	 * @param phoneNumber
	 */
	public void setPhoneNumber(String phoneNumber)
	{
		this.phoneNumber = phoneNumber;
	}

	/**
	 * Method 'getHireDate'
	 * 
	 * @return Date
	 */
	public Date getHireDate()
	{
		return hireDate;
	}

	/**
	 * Method 'setHireDate'
	 * 
	 * @param hireDate
	 */
	public void setHireDate(Date hireDate)
	{
		this.hireDate = hireDate;
	}

	/**
	 * Method 'getJobId'
	 * 
	 * @return String
	 */
	public String getJobId()
	{
		return jobId;
	}

	/**
	 * Method 'setJobId'
	 * 
	 * @param jobId
	 */
	public void setJobId(String jobId)
	{
		this.jobId = jobId;
	}

	/**
	 * Method 'getSalary'
	 * 
	 * @return float
	 */
	public float getSalary()
	{
		return salary;
	}

	/**
	 * Method 'setSalary'
	 * 
	 * @param salary
	 */
	public void setSalary(float salary)
	{
		this.salary = salary;
		this.salaryNull = false;
	}

	/**
	 * Method 'setSalaryNull'
	 * 
	 * @param value
	 */
	public void setSalaryNull(boolean value)
	{
		this.salaryNull = value;
	}

	/**
	 * Method 'isSalaryNull'
	 * 
	 * @return boolean
	 */
	public boolean isSalaryNull()
	{
		return salaryNull;
	}

	/**
	 * Method 'getCommissionPct'
	 * 
	 * @return float
	 */
	public float getCommissionPct()
	{
		return commissionPct;
	}

	/**
	 * Method 'setCommissionPct'
	 * 
	 * @param commissionPct
	 */
	public void setCommissionPct(float commissionPct)
	{
		this.commissionPct = commissionPct;
		this.commissionPctNull = false;
	}

	/**
	 * Method 'setCommissionPctNull'
	 * 
	 * @param value
	 */
	public void setCommissionPctNull(boolean value)
	{
		this.commissionPctNull = value;
	}

	/**
	 * Method 'isCommissionPctNull'
	 * 
	 * @return boolean
	 */
	public boolean isCommissionPctNull()
	{
		return commissionPctNull;
	}

	/**
	 * Method 'getManagerId'
	 * 
	 * @return int
	 */
	public int getManagerId()
	{
		return managerId;
	}

	/**
	 * Method 'setManagerId'
	 * 
	 * @param managerId
	 */
	public void setManagerId(int managerId)
	{
		this.managerId = managerId;
		this.managerIdNull = false;
	}

	/**
	 * Method 'setManagerIdNull'
	 * 
	 * @param value
	 */
	public void setManagerIdNull(boolean value)
	{
		this.managerIdNull = value;
	}

	/**
	 * Method 'isManagerIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isManagerIdNull()
	{
		return managerIdNull;
	}

	/**
	 * Method 'getDepartmentId'
	 * 
	 * @return int
	 */
	public int getDepartmentId()
	{
		return departmentId;
	}

	/**
	 * Method 'setDepartmentId'
	 * 
	 * @param departmentId
	 */
	public void setDepartmentId(int departmentId)
	{
		this.departmentId = departmentId;
		this.departmentIdNull = false;
	}

	/**
	 * Method 'setDepartmentIdNull'
	 * 
	 * @param value
	 */
	public void setDepartmentIdNull(boolean value)
	{
		this.departmentIdNull = value;
	}

	/**
	 * Method 'isDepartmentIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isDepartmentIdNull()
	{
		return departmentIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Employees)) {
			return false;
		}
		
		final Employees _cast = (Employees) _other;
		if (employeeId != _cast.employeeId) {
			return false;
		}
		
		if (firstName == null ? _cast.firstName != firstName : !firstName.equals( _cast.firstName )) {
			return false;
		}
		
		if (lastName == null ? _cast.lastName != lastName : !lastName.equals( _cast.lastName )) {
			return false;
		}
		
		if (email == null ? _cast.email != email : !email.equals( _cast.email )) {
			return false;
		}
		
		if (phoneNumber == null ? _cast.phoneNumber != phoneNumber : !phoneNumber.equals( _cast.phoneNumber )) {
			return false;
		}
		
		if (hireDate == null ? _cast.hireDate != hireDate : !hireDate.equals( _cast.hireDate )) {
			return false;
		}
		
		if (jobId == null ? _cast.jobId != jobId : !jobId.equals( _cast.jobId )) {
			return false;
		}
		
		if (salary != _cast.salary) {
			return false;
		}
		
		if (salaryNull != _cast.salaryNull) {
			return false;
		}
		
		if (commissionPct != _cast.commissionPct) {
			return false;
		}
		
		if (commissionPctNull != _cast.commissionPctNull) {
			return false;
		}
		
		if (managerId != _cast.managerId) {
			return false;
		}
		
		if (managerIdNull != _cast.managerIdNull) {
			return false;
		}
		
		if (departmentId != _cast.departmentId) {
			return false;
		}
		
		if (departmentIdNull != _cast.departmentIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + employeeId;
		if (firstName != null) {
			_hashCode = 29 * _hashCode + firstName.hashCode();
		}
		
		if (lastName != null) {
			_hashCode = 29 * _hashCode + lastName.hashCode();
		}
		
		if (email != null) {
			_hashCode = 29 * _hashCode + email.hashCode();
		}
		
		if (phoneNumber != null) {
			_hashCode = 29 * _hashCode + phoneNumber.hashCode();
		}
		
		if (hireDate != null) {
			_hashCode = 29 * _hashCode + hireDate.hashCode();
		}
		
		if (jobId != null) {
			_hashCode = 29 * _hashCode + jobId.hashCode();
		}
		
		_hashCode = 29 * _hashCode + Float.floatToIntBits(salary);
		_hashCode = 29 * _hashCode + (salaryNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(commissionPct);
		_hashCode = 29 * _hashCode + (commissionPctNull ? 1 : 0);
		_hashCode = 29 * _hashCode + managerId;
		_hashCode = 29 * _hashCode + (managerIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + departmentId;
		_hashCode = 29 * _hashCode + (departmentIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EmployeesPk
	 */
	public EmployeesPk createPk()
	{
		return new EmployeesPk(employeeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.gm.hxOracle.dto.Employees: " );
		ret.append( "employeeId=" + employeeId );
		ret.append( ", firstName=" + firstName );
		ret.append( ", lastName=" + lastName );
		ret.append( ", email=" + email );
		ret.append( ", phoneNumber=" + phoneNumber );
		ret.append( ", hireDate=" + hireDate );
		ret.append( ", jobId=" + jobId );
		ret.append( ", salary=" + salary );
		ret.append( ", commissionPct=" + commissionPct );
		ret.append( ", managerId=" + managerId );
		ret.append( ", departmentId=" + departmentId );
		return ret.toString();
	}

}
