/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.gm.hxOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the EMPLOYEES table.
 */
public class EmployeesPk implements Serializable
{
	protected int employeeId;

	/** 
	 * This attribute represents whether the primitive attribute employeeId is null.
	 */
	protected boolean employeeIdNull;

	/** 
	 * Sets the value of employeeId
	 */
	public void setEmployeeId(int employeeId)
	{
		this.employeeId = employeeId;
	}

	/** 
	 * Gets the value of employeeId
	 */
	public int getEmployeeId()
	{
		return employeeId;
	}

	/**
	 * Method 'EmployeesPk'
	 * 
	 */
	public EmployeesPk()
	{
	}

	/**
	 * Method 'EmployeesPk'
	 * 
	 * @param employeeId
	 */
	public EmployeesPk(final int employeeId)
	{
		this.employeeId = employeeId;
	}

	/** 
	 * Sets the value of employeeIdNull
	 */
	public void setEmployeeIdNull(boolean employeeIdNull)
	{
		this.employeeIdNull = employeeIdNull;
	}

	/** 
	 * Gets the value of employeeIdNull
	 */
	public boolean isEmployeeIdNull()
	{
		return employeeIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EmployeesPk)) {
			return false;
		}
		
		final EmployeesPk _cast = (EmployeesPk) _other;
		if (employeeId != _cast.employeeId) {
			return false;
		}
		
		if (employeeIdNull != _cast.employeeIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + employeeId;
		_hashCode = 29 * _hashCode + (employeeIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.gm.hxOracle.dto.EmployeesPk: " );
		ret.append( "employeeId=" + employeeId );
		return ret.toString();
	}

}
